### ISSUE TITLE
2.4 version pre-aggregated query results are inaccurate

### ISSUE THREAD

**Issue by yujimoyouran** [OpenTSDB/opentsdb#1337] opened 2018-09-12 06:59 UTC
This is my configuration term：
```
{
            "table": "tsdb-rollup-7d",
            "preAggregationTable": "tsdb-rollup-preagg-7d",
            "interval": "4h",
            "rowSpan": "168h"
        },
```
For example: now it is 15:00, 2018-9-12. I inserted the data of 2018-9-12 00:00 as:
```
{
"Aggregator" : "sum",
"GroupByAggregator" : "sum",
"Interval" : "4 h",
"Metric" : "sys. Sum. The CPU,
"Tags" : {
"Age", "age",
"Dc" : "dc2,"
"The host" : "host",
"IP" : "ip4",
"Name" : "name",
"Port", "port73",
"Service", "service22"
},
"Timestamp" : 1536681600,
"Value" : 1.
}
```

I have no results from 2018-9-12 00:00 to 2018-9-12 04:00, such as:

```
{
	"start": 1536681600,
	"end":1536696000,
    "timezone":"UTC",
	"queries": [{
			"aggregator": "sum",
			"metric": "sys.sum.cpu",
			"preAggregate":"true",
			"downsample":"4h-sum",
			"explicitTags":false,
			"rollupUsage":"ROLLUP_NOFALLBACK",
			"rate": "false",
			"filters": [
                {
                   "type":"literal_or",
                   "tagk":"host",
                   "filter":"host",
                   "groupBy":false
                }
			]
		}
	]
}
```
However, if I change it to the following (no end time specified), I get the right result：
```
{
	"start": 1536681600,
    "timezone":"UTC",
	"queries": [{
			"aggregator": "sum",
			"metric": "sys.sum.cpu",
			"preAggregate":"true",
			"downsample":"4h-sum",
			"explicitTags":false,
			"rollupUsage":"ROLLUP_NOFALLBACK",
			"rate": "false",
			"filters": [
                {
                   "type":"literal_or",
                   "tagk":"host",
                   "filter":"host",
                   "groupBy":false
                }
			]
		}
	]
}
```

Who can tell me why? thank you

**Comment by manolama** [comment] 2018-12-12 02:18
Hmm, I was unable to reproduce this one. I copied the data, fixed the tags and it queried properly even with 1 hour time-range. E.g.

Data:
```
[
    [{
	"aggregator": "sum",
	"groupByAggregator": "sum",
	"interval": "4h",
	"metric": "sys.cpu.user",
	"tags": {
		"Age": "age",
		"Dc": "dc2",
		"Thehost": "host",
		"IP": "ip4",
		"Name": "name"
	},
	"timestamp": 1536681600,
	"value": 1
}]
]
```

Query:
```
{
	"start": 1536681600,
	"end":1536685200,
	"timezone": "UTC",
	"queries": [{
		"aggregator": "sum",
		"metric": "sys.cpu.user",
		"preAggregate": "true",
		"downsample": "4h-sum",
		"explicitTags": false,
		"rollupUsage": "ROLLUP_NOFALLBACK",
		"rate": "false",
		"filters": [{
			"type": "literal_or",
			"tagk": "Thehost",
			"filter": "host",
			"groupBy": false
		}]
	}]
}
```

Result:
```[
    {
        "metric": "sys.cpu.user",
        "tags": {
            "_aggregate": "SUM",
            "IP": "ip4",
            "Thehost": "host",
            "Age": "age",
            "Dc": "dc2",
            "Name": "name"
        },
        "aggregateTags": [],
        "dps": {
            "1536681600": 1
        }
    }
]
```

I'll close this for now.

**Closed by manolama** 2018-12-12 02:18 UTC
Labels: bug
