### ISSUE TITLE
please help me look this error,thank you!

### ISSUE THREAD

**Issue by piaoyingfeimeng** [OpenTSDB/opentsdb#1099] opened 2017-11-08 09:40 UTC
2017-11-08 17:35:43,766 INFO  [main] ZooKeeper: Initiating client connection, connectString=10.58.53.21:2181 sessionTimeout=5000 watcher=org.hbase.async.HBaseClient$ZKClient@6ff086d7
2017-11-08 17:35:43,777 INFO  [main] HBaseClient: Need to find the -ROOT- region
2017-11-08 17:35:43,780 INFO  [main-SendThread(10.58.53.21:2181)] ClientCnxn: Opening socket connection to server 10.58.53.21/10.58.53.21:2181. Will not attempt to authenticate using SASL (unknown error)
2017-11-08 17:35:43,783 INFO  [main-SendThread(10.58.53.21:2181)] ClientCnxn: Socket connection established to 10.58.53.21/10.58.53.21:2181, initiating session
2017-11-08 17:35:43,791 INFO  [main-SendThread(10.58.53.21:2181)] ClientCnxn: Session establishment complete on server 10.58.53.21/10.58.53.21:2181, sessionid = 0x15d3a8c3be1bf65, negotiated timeout = 5000
2017-11-08 17:35:43,811 INFO  [main-EventThread] HBaseClient: Connecting to .META. region @ 10.58.188.33:16201
2017-11-08 17:35:43,850 INFO  [main-EventThread] ZooKeeper: Session: 0x15d3a8c3be1bf65 closed
2017-11-08 17:35:43,850 INFO  [main-EventThread] ClientCnxn: EventThread shut down
2017-11-08 17:35:43,906 INFO  [main] TSDB: Flushing compaction queue
2017-11-08 17:35:43,908 INFO  [main] HBaseClient: Channel [id: 0xac0e10d5, /10.58.188.35:56549 => /10.58.188.33:16201] is disconnecting: [id: 0xac0e10d5, /10.58.188.35:56549 => /10.58.188.33:16201] DISCONNECT
2017-11-08 17:35:43,908 INFO  [main] HBaseClient: Lost connection with the .META. region
2017-11-08 17:35:43,911 INFO  [main] TSDB: Completed shutting down the TSDB
Exception in thread "main" java.lang.RuntimeException: Initialization failed
        at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: com.stumbleupon.async.DeferredGroupException: At least one of the Deferreds failed, first exception:
        at com.stumbleupon.async.DeferredGroup.done(DeferredGroup.java:169)
        at com.stumbleupon.async.DeferredGroup.recordCompletion(DeferredGroup.java:142)
        at com.stumbleupon.async.DeferredGroup.access$000(DeferredGroup.java:36)
        at com.stumbleupon.async.DeferredGroup$1Notify.call(DeferredGroup.java:82)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.access$300(Deferred.java:430)
        at com.stumbleupon.async.Deferred$Continue.call(Deferred.java:1366)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1313)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1284)
        at com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1257)
        at com.stumbleupon.async.Deferred.callback(Deferred.java:1005)
        at org.hbase.async.HBaseRpc.callback(HBaseRpc.java:712)
        at org.hbase.async.RegionClient.decode(RegionClient.java:1533)
        at org.hbase.async.RegionClient.decode(RegionClient.java:88)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.hbase.async.RegionClient.handleUpstream(RegionClient.java:1223)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.hbase.async.HBaseClient$RegionClientPipeline.sendUpstream(HBaseClient.java:3121)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.hbase.async.TableNotFoundException: "tsdb"
        at org.hbase.async.HBaseClient$7.call(HBaseClient.java:2315)
        at org.hbase.async.HBaseClient$7.call(HBaseClient.java:2312)
        at com.stumbleupon.async.Deferred.doCall(Deferred.java:1278)
        ... 33 more

**Comment by ZHANGGUOQING91** [comment] 2017-11-08 18:31
hello,
    this question source of your hbaseclient can not find your region path ,please check the hbase in zk Zookeeper Base Path Path, you should make the Zookeeper Base Path configuration to opentsdb.conf. the content is tsd.storage.hbase.zk_basedir=Zookeeper Base Path , defaults to /hbase.

**Comment by ZHANGGUOQING91** [comment] 2017-11-08 18:32
hello,
    this question source of your hbaseclient can not find your region path ,please check the hbase in zk Zookeeper Base Path Path, you should make the Zookeeper Base Path configuration to opentsdb.conf. the content is tsd.storage.hbase.zk_basedir=Zookeeper Base Path , defaults to /hbase.

**Comment by ZHANGGUOQING91** [comment] 2017-11-08 18:32
hello,
    this question source of your hbaseclient can not find your region path ,please check the hbase in zk Zookeeper Base Path Path, you should make the Zookeeper Base Path configuration to opentsdb.conf. the content is tsd.storage.hbase.zk_basedir=Zookeeper Base Path , defaults to /hbase.

**Comment by IDerr** [comment] 2017-11-10 00:10
Hi, 
This line 
```
2017-11-08 17:35:43,908 INFO [main] HBaseClient: Lost connection with the .META. region
```
seems to indicate that opentsdb has lost the connection with hbase, you should check that :)

**Comment by johnewing1** [comment] 2017-11-10 10:17
The issue is that you have run the script to create the tsdb tables yet

5 lines from the bottom of your stack trace
Caused by: org.hbase.async.TableNotFoundException: "tsdb"

**Comment by IDerr** [comment] 2017-11-10 10:18
@manolama you can close this issue

**Comment by johnewing1** [comment] 2017-11-10 11:17
This is a super common problem for people to get stuck on because the information you need is buried in the middle of a stack trace. Could the this exception be caught, and a more user-friendly error message be printed before exiting ?

**Comment by lunayach** [comment] 2017-12-14 18:40
I have created the tables twice, obviously, that's not the issue.

**Comment by johann8384** [comment] 2017-12-14 22:22
You've got an issue with HBase, I would check the following three things:

1) The HBase path in Zookeeper matches the path you configured in the
OpenTSDB Config
2) The OpenTSDB Tables exist in HBase and all of the regions are
available/healthy
3)The table names in the OpenTSDB configuration match the names in HBase

**Closed** 2018-12-11 23:51 UTC
Labels: question

**Comment by MikeKulls2** [comment] 2019-01-30 00:08
I had this issue on MapR with a secure cluster. Turned out I had a ticket created but TSDB couldn't see the ticket. I had to add the below line to the file /usr/share/opentsdb/etc/init.d/opentsdb

export MAPR_TICKETFILE_LOCATION=/opt/mapr/conf/tickets/root

Note path of either file could be different on another system
