### ISSUE TITLE
HBaseClient: Lost connection with the .META. region

### ISSUE THREAD

**Issue by wsszh** [OpenTSDB/opentsdb#893] opened 2016-11-17 11:17 UTC
Hello.
I try to compile and install the source code, but failed...
Every time I try ./build/tsdb tsd, I have the same issue...

![qd2c9hd4 fciwsf2kjfwev](https://cloud.githubusercontent.com/assets/13674529/20387282/5409ba08-acfa-11e6-8704-4954f0de7f77.png)

Can anyone help me? 
T^T

**Comment by johann8384** [comment] 2016-11-17 13:47
It looks like you need to set the path for the Zookeeper base directory.

tsd.storage.hbase.zk_basedir

This should be /hbase-unsecure  on some distributions.

Either that or the error you are getting is caused by the OpenTSDB tables
not existing yet. I forget which this early in the morning. :)

**Comment by wsszh** [comment] 2016-11-17 17:15
@johann8384 Thanks a lot for your reply! But after I set the path for the Zookeeper base directory, the info about the issue is:
![20161118010602](https://cloud.githubusercontent.com/assets/13674529/20399258/31a56378-ad2b-11e6-9d65-2199985361c1.png)
P.S. the mode of the hbase and zookeeper is standalone...
Please help me...:(

**Comment by wsszh** [comment] 2016-11-17 17:17
@johann8384 Oh, I forgot to say that I have created 4 tables successfully before I try to start opentsdb...

**Comment by johann8384** [comment] 2016-11-17 17:35
Definitely looks like the base directory is wrong, or perhaps the Zookeeper
OpenTSDB is connecting to is not the same as the one HBase is using?

Did you use the Zookeeper client to confirm the HBase data is in the path
you specified?

**Comment by wsszh** [comment] 2016-11-18 02:04
@johann8384 Hi. I just set the default value "/hbase" for the Zookeeper base directory: 
![20161118100106](https://cloud.githubusercontent.com/assets/13674529/20415840/f39834ca-ad75-11e6-82ab-8183634d2c99.png)

And here's my hbase-site.xml: 
![20161118100241](https://cloud.githubusercontent.com/assets/13674529/20415881/2c8593ae-ad76-11e6-8254-364af6ab2200.png)

I don't know what's wrong with this...:(

**Comment by johann8384** [comment] 2016-11-18 03:15
Use the Zookeeper client. Do "ls /" see what paths you have, see if you can
find the Hbase metadata there.

**Comment by wsszh** [comment] 2016-11-18 03:28
@johann8384 I did what you say, and here's the result: 
![20161118112826](https://cloud.githubusercontent.com/assets/13674529/20417688/261351b2-ad82-11e6-9ab6-091a9471ec00.png)
Is it right?

**Comment by wsszh** [comment] 2016-11-18 03:40
@johann8384 Hello. I did what you say, and here's the result: 
![20161118113859](https://cloud.githubusercontent.com/assets/13674529/20417889/a041281e-ad83-11e6-8385-aa2723b49201.png)

Is it right?

**Comment by manolama** [comment] 2016-11-27 20:13
Hi @wsszh, are you able to read and write to the TSD? That ``Lost connection with the .META. region`` message is normal as the client will close it's connection to the server where the meta region is located after it hasn't been read to in some time (which is why it's marked as ``INFO``). If that's the only notice you're seeing then you should be in good shape.

**Comment by wsszh** [comment] 2016-11-28 01:22
@manolama Thanks for your reply ! As you said, I found it just a normal message and everything is working right. I will close this issue now : )

**Closed** 2016-11-28 01:22 UTC
Labels: question
