### ISSUE TITLE
hangs up after eating up all available heap

### ISSUE THREAD

**Issue by olegfedoseev** [OpenTSDB/opentsdb#542] opened 2015-08-05 06:53 UTC
I running `OpenTSDB version [2.1.0RC1] built from revision 2335ecd`  with 3 node hbase cluster.

I tried to set heap size to 8, 16, 24, 32Gb and it always eat it up and "hangs".
Symptoms: web interface response time increase, or it even stop responding. Client, writing metrics to via telnet interface is able to connect and send metrics, but time to write to socket can increase from second to hours.

I'm no java guy, so i don't know where to look.

**Comment by olegfedoseev** [comment] 2015-08-26 08:58
Any ideas? Any direction where to look?

**Comment by manolama** [comment] 2015-08-27 04:47
Hi, sorry. The first place to look would be the ``/api/stats`` counters for your TSDs. In particular look at the HBase errors and NSREs. What can happen, particularly if you have a lot of regions, is a region server splits a bunch of regions or if the server fails and regions migrate, the RPCs for those regions will back up in a queue in TSDB and you can run out of heap. So take a look there first.

Also check your region servers (UI and logs) and see how often regions are moving, splitting etc. And if you are using the real-time meta sync settings, try disabling those and see if the situation improves.

**Comment by olegfedoseev** [comment] 2015-08-27 10:17
I have graph for all stats, and already tried to find something, that was linked to the problem.
But unfortunately, there is no errors of any kind, region splits happens nowhere near problem time.
And i'm not using real-time meta sync.

I'll check, once again, region servers logs, but last time there was lots and lots of logs and nothing out of the ordinary.

**Comment by KurtYoung** [comment] 2015-08-28 01:27
We meet this problem before, and our root cause is we send metrics via telnet, and if the request is success, TSD server will not respond anything. But if the request is failed, (maybe the name or some tag is invalid), however TSD server will return some error_msg, but our client did not read these messages, they all stuck in TSD's output buffer, that's what eat up the heap.

**Comment by olegfedoseev** [comment] 2015-08-28 05:03
@KurtYoung hmm, interesting! It's may be the cause. I'll check this right away :)

**Comment by olegfedoseev** [comment] 2015-08-28 08:34
@KurtYoung looks like you were right! Deployed fixed version of "metrics sender", and so far so good.

@manolama this behaviour looks like bug to me. If client decided not to read, maybe OpenTSDB should just discard such messages after some time. Of with circular buffer of some kind?

**Comment by mxk1235** [comment] 2015-08-28 20:29
we had a similar problem.  it definitely seems wonky that tsd allows the connected client to put it into that state.  however, i think the right course of action is disconnecting the client and dropping the buffered messages.

**Comment by manolama** [comment] 2015-08-28 20:35
@KurtYoung yeah, I actually have a patch to upstream that will simply stop writing to the channel if the buffer is full, thus avoiding the memory consumption.

@mxk1235 We could disconnect but for existing scripts, they don't expect that behavior so for now we can just block writes. We really should add a proper alternative to Telnet like Protobufs or something. Well, aside from HTTP.

**Comment by mxk1235** [comment] 2015-08-28 20:55
that's true, the behavior change may be breaking, although for a telnet interface, reconnects should be implied.  i suppose there would be use cases for telnet connections to behave in many different ways, which had a brief discussion over in https://github.com/OpenTSDB/opentsdb/issues/515

**Comment by manolama** [comment] 2015-08-30 21:16
Actually this is handled in 2.2 where we will now stop writing to the socket when it's blocked. I'll close this guy for now.

**Closed by manolama** 2015-08-30 21:16 UTC
Labels: question

**Comment by utkarshcmu** [comment] 2016-03-29 22:08
@manolama I am facing the same issue, I have given my TSDB instance 24GB of Heap Memory and TSDB just uses all and hangs up. Even stopping TSDB results in FAILURE.

**Comment by manolama** [comment] 2016-09-27 21:02
Re: @utkarshcmu Try setting ``hbase.nsre.high_watermark`` to a much smaller number like ``100``. This can cause OOMs if HBase is splitting or moving regions.
