### ISSUE TITLE
Frequently query for the lastest OpenTSDB  error

### ISSUE THREAD

**Issue by HallsHalls** [OpenTSDB/opentsdb#545] opened 2015-08-16 08:31 UTC
Recently our team upgrade the openTSDB version 2.1.0 in branch of 'next' 

operate by send many same parameter query  in a short time will response the result ,although wait for few minutes the error still become, but i change the time range the result will be back quickly.

like that
```json
{"error":{"code":500,"message":"Query is already executing for endpoint: /1x.xx.xx.xx:9999","trace":"net.opentsdb.core.QueryException: Query is already executing for endpoint: /1x.xx.xx.xx:9999n\tat net.opentsdb.stats.QueryStats.<init>(QueryStats.java:124) ~[tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat net.opentsdb.tsd.QueryRpc.handleQuery(QueryRpc.java:125) ~[tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat net.opentsdb.tsd.QueryRpc.execute(QueryRpc.java:87) ~[tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DjavascriptefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.me0.64.215.39:45610ssageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]\n\tat net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:87) [tsdb-2.2.0-SNAPSHOT.jar:4725332]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat javascriptorg.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]\n\tat java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]\n"}}
```

**Comment by manolama** [comment] 2015-08-27 04:42
Hmm, I may need to disable that code path then. The idea was to prevent someone from a single machine sending the same query over and over without waiting for the result. If you run it from multiple machines you shouldn't see the error.

**Comment by manolama** [comment] 2015-08-30 20:42
Pushed a fix to the "next" branch. Try disabling "tsd.query.allow_simultaneous_duplicates" in your config and let us know what happens.

**Closed by manolama** 2015-08-30 20:42 UTC
Labels: bug

**Comment by HallsHalls** [comment] 2015-08-31 01:07
Thanks, that was great help for us !

**Comment by alienth** [comment] 2015-09-15 22:44
@manolama We're getting this now, as well. On a build of next from ~6 days ago. Our config doesn't set `tsd.query.allow_simultaneous_duplicates`, and that config option defaults to False, so that doesn't appear to be our issue.

We're still using appends, if that matters.

**Comment by manolama** [comment] 2015-09-15 23:10
@alienth It could be, this means that either there's a bug in the hash coding or you really do have a number of queries coming in at the same time for the same data while a query is still running.
Try setting ``tsd.query.allow_simultaneous_duplicates`` to true and see if that solves it. If not then it's definitely a bug.

**Comment by alienth** [comment] 2015-09-15 23:19
I'll give that a try. Thanks!

Curiously, I can't get a manual repo by running a bunch of simultaneous queries for the same data.

**Comment by manolama** [comment] 2015-09-15 23:26
hmm, when you tried your queries, where they fairly long running or pretty responsive? Ask for a few months of data and hopefully that'll reproduce it.

**Comment by alienth** [comment] 2015-09-15 23:29
I'm testing with queries which take about 30 seconds to return. Super high
cardinality metrics.

**Comment by manolama** [comment] 2015-09-15 23:38
hmm, and were you asking for /api/query/last or just /api/query?

**Comment by alienth** [comment] 2015-09-15 23:41
Just `/api/query`. I missed that this ticket is probably referring to last.

TBH we actually want to support simultaneous duplicate queries due to things like Grafana dashboards, so I'll probably keep that setting enabled and see how things go. Curious that it was occasionally tossing exceptions and that I can't get it to repro, tho. :confused:

**Comment by manolama** [comment] 2015-09-15 23:42
Were you using relative timestamps in the queries too or absolute?

**Comment by alienth** [comment] 2015-09-15 23:44
Absolute.

**Comment by manolama** [comment] 2015-09-15 23:45
that really should have popped it then. grr. Keep trying it and if you do see it pop up again try running /api/query/stats and dump that in a ticket please.
