### ISSUE TITLE
/api/query  raw  datapoint  count 

### ISSUE THREAD

**Issue by youzhagui2006** [OpenTSDB/opentsdb#782] opened 2016-04-21 08:25 UTC
when use Query API Endpoints  “ /api/query ”   ,  how  get   raw  datapoint  count

**Comment by manolama** [comment] 2016-05-01 18:38
Sorry that didn't make it in to 2.2.0, I'll restore it in 2.2.1

**Comment by manolama** [comment] 2016-05-01 19:23
Closing as dupe of #784

**Closed by manolama** 2016-05-01 19:23 UTC
Labels: bug
