### ISSUE TITLE
There is a  bug can run any command on linux when use opentsdb ui 

### ISSUE THREAD

**Issue by xiaom0-0** [OpenTSDB/opentsdb#793] opened 2016-05-11 03:05 UTC
if there is a wrong parameter such like "wxh=1900x770\`ls /home/\`" it will cause an "IllegalArgumentException",And then be  process with "badRequest"  , because this response with "PNG" , the wrong parameter will be worte to a script ,add run。

there is a sample way to fix it temporarily
`---a/expand/opentsdb/src/tsd/HttpQuery.java
+++ b/expand/opentsdb/src/tsd/HttpQuery.java
@@ -421,8 +421,8 @@ final class HttpQuery extends AbstractHttpQuery {
       HttpQuery.escapeJson(exception.getMessage(), buf);
       buf.append("\"}");
       sendReply(HttpResponseStatus.BAD_REQUEST, buf);
-    } else if (hasQueryStringParam("png")) {
-      sendAsPNG(HttpResponseStatus.BAD_REQUEST, exception.getMessage(), 3600);
+    //} else if (hasQueryStringParam("png")) {
+      //sendAsPNG(HttpResponseStatus.BAD_REQUEST, exception.getMessage(), 3600);
     } else {
       sendReply(HttpResponseStatus.BAD_REQUEST,
                 makePage("Bad Request", "Looks like it's your fault this time",`

**Comment by manolama** [comment] 2016-05-11 17:47
Eww, thank you very much for finding this. Will patch it shortly.

**Comment by gsocgsoc** [comment] 2016-05-12 15:01
Seems like a duplicate of #781

**Closed** 2016-09-19 23:52 UTC
Labels: bug
